version: '3.8'

services:

  hacker-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=sample_db
      - POSTGRES_USER=sample_user
      - POSTGRES_PASSWORD=sample_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  backend:
#    build:
#      context: ../backend
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "8000:8000"
#    volumes:
#      - static_value:/app/backend_static/
#      - media_value:/app/backend_media/
#    depends_on:
#      - hacker-db
#
#  frontend:
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "3000:3000"
#    environment:
#      - NODE_ENV=development
#    volumes:
#      - frontend_build:/app/result_build/
#
#  nginx:
#    image: nginx:latest
#    restart: always
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - frontend_build:/usr/share/nginx/html/
#      - static_value:/var/html/backend_static/
#      - media_value:/var/html/backend_media/
#    depends_on:
#      - backend
#      - frontend

volumes:
  db_data:
