# Generated by Django 3.2 on 2024-04-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Количество комментариев')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-date_time',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('children', models.ManyToManyField(blank=True, related_name='_news_comment_children_+', to='news.Comment', verbose_name='Ответы на комментарий')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-date_time',),
            },
        ),
    ]
